CC=pdflatex

build:
	pdflatex Rapport.tex
	rm -rf *.aux
	rm -rf *.log
	rm -rf Rapport.synctex.gz
	rm -rf *.toc
	
clean:
	rm -rf Rapport.pdf
	rm -rf *.aux
	rm -rf *.log
	rm -rf Rapport.synctex.gz
	rm -rf *.toc
